package com.example.gotouchgrass.data.auth

import io.github.jan.supabase.SupabaseClient
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.auth.providers.builtin.Email
import io.github.jan.supabase.postgrest.from
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

class AuthService(
    private val supabaseClient: SupabaseClient
) {

    private companion object {
        const val TABLE_USERS = "user"
    }

    suspend fun signUp(
        email: String,
        password: String,
        displayName: String
    ): Result<AuthUser> = runCatching {
        // Attempt sign-up first.
        val signUpResult = runCatching {
            supabaseClient.auth.signUpWith(Email) {
                this.email = email
                this.password = password
            }
        }

        // code until line 58 generated by GPT-5.3-Codex
        if (signUpResult.isFailure) {
            val message = signUpResult.exceptionOrNull()?.message?.lowercase().orEmpty()
            val userAlreadyExists =
                message.contains("already") ||
                    message.contains("exists") ||
                    message.contains("registered")

            if (!userAlreadyExists) {
                throw signUpResult.exceptionOrNull() ?: Exception("Sign up failed")
            }
        }

        val authUser = signInAndGetCurrentUser(email, password)
            ?: throw Exception(
                "Account exists but sign-in failed. Verify email/password, or reset/delete the user in Supabase Auth and try again."
            )

        ensureUserProfile(
            authUserId = authUser.id,
            email = authUser.email ?: email,
            displayName = displayName
        ).getOrElse { error ->
            throw Exception(
                "Auth account created, but profile row insert failed. Check RLS policy for public.\"user\" and unique constraints. Details: ${error.message}",
                error
            )
        }

        AuthUser(
            id = authUser.id,
            email = authUser.email ?: email,
            displayName = displayName
        )
    }

    suspend fun signIn(
        email: String,
        password: String
    ): Result<AuthUser> = runCatching {
        val authUser = signInAndGetCurrentUser(email, password)
            ?: throw Exception("Sign in failed: invalid credentials")

        ensureUserProfile(
            authUserId = authUser.id,
            email = authUser.email ?: email,
            displayName = authUser.userMetadata?.get("display_name") as? String ?: "User"
        )

        AuthUser(
            id = authUser.id,
            email = authUser.email ?: email,
            displayName = authUser.userMetadata?.get("display_name") as? String ?: "User"
        )
    }

    suspend fun getCurrentUser(): Result<AuthUser?> = runCatching {
        val authUser = supabaseClient.auth.currentUserOrNull()
        authUser?.let {
            AuthUser(
                id = it.id,
                email = it.email ?: "",
                displayName = it.userMetadata?.get("display_name") as? String ?: "User"
            )
        }
    }

    suspend fun signOut(): Result<Unit> = runCatching {
        supabaseClient.auth.signOut()
    }

    private suspend fun signInAndGetCurrentUser(email: String, password: String) = runCatching {
        supabaseClient.auth.signInWith(Email) {
            this.email = email
            this.password = password
        }
        supabaseClient.auth.currentUserOrNull()
    }.getOrNull()

    // Best-effort profile creation so auth success is not blocked by profile table drift/RLS.
    private suspend fun ensureUserProfile(
        authUserId: String,
        email: String,
        displayName: String
    ): Result<Unit> {
        val username = buildUsername(displayName, email, authUserId)
        return runCatching {
            supabaseClient.from(TABLE_USERS).insert(
                UserProfileInsert(
                    authUserId = authUserId,
                    displayName = displayName,
                    username = username,
                    email = email,
                    level = 1,
                    xpTotal = 0
                )
            )
        }
    }

    private fun buildUsername(displayName: String, email: String, authUserId: String): String {
        val base = displayName
            .trim()
            .lowercase()
            .replace(Regex("[^a-z0-9]+"), "_")
            .trim('_')

        val fallback = email.substringBefore("@").lowercase()
        val prefix = (if (base.isNotBlank()) base else fallback)
            .replace(Regex("[^a-z0-9_]+"), "_")
            .trim('_')
            .ifBlank { "user" }
            .take(16)

        val suffix = authUserId.replace("-", "").takeLast(6).lowercase()
        return "${prefix}_$suffix"
    }
}


@Serializable
private data class UserProfileInsert(
    @SerialName("auth_user_id") val authUserId: String,
    @SerialName("display_name") val displayName: String,
    val username: String,
    val email: String,
    val level: Int,
    @SerialName("xp_total") val xpTotal: Int
)


data class AuthUser(
    val id: String,
    val email: String,
    val displayName: String
)
