package com.example.gotouchgrass.data

import com.example.gotouchgrass.data.supabase.ChallengeProgressRow
import com.example.gotouchgrass.data.supabase.ChallengeRow
import com.example.gotouchgrass.data.supabase.FriendRequestRow
import com.example.gotouchgrass.data.supabase.RouteRow
import com.example.gotouchgrass.data.supabase.SearchActivityInsert
import com.example.gotouchgrass.data.supabase.SupabaseDataSource
import com.example.gotouchgrass.data.supabase.UserSettingsUpsert
import com.example.gotouchgrass.data.supabase.StreakUpsert
import com.example.gotouchgrass.data.supabase.VisitSessionInsert
import com.example.gotouchgrass.domain.FriendMapMarker
import com.example.gotouchgrass.domain.TripZone
import com.example.gotouchgrass.domain.ChallengeTimeWindow
import com.example.gotouchgrass.domain.ChallengeType
import com.example.gotouchgrass.domain.ExploreChallengeItem
import com.example.gotouchgrass.domain.ExploreRouteItem
import com.example.gotouchgrass.domain.LatLng
import com.example.gotouchgrass.domain.LeaderboardData
import com.example.gotouchgrass.domain.LifetimeStats
import com.example.gotouchgrass.domain.RouteDifficulty
import com.example.gotouchgrass.domain.RouteTheme
import com.example.gotouchgrass.domain.StreakData
import com.example.gotouchgrass.domain.User
import com.example.gotouchgrass.domain.UserPreferences
import com.example.gotouchgrass.domain.WeeklySummary
import com.example.gotouchgrass.domain.isValidAvatarPresetKey
import com.example.gotouchgrass.domain.rarityScoreForLandmarkCategoryName
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.json.JSONObject
import com.google.android.gms.maps.model.LatLng as GmsLatLng
import java.time.DayOfWeek
import java.time.LocalDate
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

open class GoTouchGrassRepository(
    private val dataSource: SupabaseDataSource
) : ExploreRepository {
    enum class SearchEventSource {
        RESULT, RECENT, TRENDING
    }

    // User
    suspend fun getUser(userId: String): Result<User?> = dataSource.getUserById(userId)

    suspend fun updateUserProfile(
        userId: String,
        username: String,
        displayName: String,
        avatarKey: String?
    ): Result<Unit> = runCatching {
        val trimmedUsername = username.trim()
        val trimmedDisplayName = displayName.trim()
        require(trimmedUsername.isNotEmpty()) { "Username cannot be empty" }
        require(trimmedDisplayName.isNotEmpty()) { "Display name cannot be empty" }
        require(isValidAvatarPresetKey(avatarKey)) { "Invalid avatar preset" }
        dataSource.updateUserProfileByAuthId(userId, trimmedUsername, trimmedDisplayName, avatarKey)
    }

    // Explore page

    override suspend fun getTotalXp(userId: String): Result<Int> = runCatching {
        dataSource.getUserById(userId).getOrThrow()?.xpTotal ?: 0
    }

    override suspend fun getChallenges(
        userId: String, timeWindow: ChallengeTimeWindow
    ): Result<List<ExploreChallengeItem>> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching emptyList()

        val challenges = dataSource.fetchChallenges(timeWindow.name)
        val progressMap =
            dataSource.fetchChallengeProgress(userRow.id).associateBy { it.challengeId }

        challenges.map { ch -> ch.toExploreChallengeItem(progressMap[ch.id]) }
    }

    suspend fun getRecentSearches(userId: String, limit: Int = 8): Result<List<String>> =
        runCatching {
            val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching emptyList()

            dataSource.fetchRecentSearchActivity(userRow.id, limit * 3).map { it.queryText.trim() }
                .filter { it.isNotBlank() }.distinctBy { it.lowercase() }.take(limit)
        }

    // function logic generated by Claude Sonnet 4.6
    suspend fun getTrendingSearches(limit: Int = 5): Result<List<String>> = runCatching {
        val rows = dataSource.fetchRecentGlobalSearchActivity(300)
        val grouped = rows.map { it.queryText.trim() }.filter { it.isNotBlank() }
            .groupingBy { it.lowercase() }.eachCount()

        val canonicalByKey = rows.map { it.queryText.trim() }.filter { it.isNotBlank() }
            .associateBy { it.lowercase() }

        grouped.entries.sortedWith(compareByDescending<Map.Entry<String, Int>> { it.value }.thenBy { it.key })
            .map { entry -> canonicalByKey[entry.key] ?: entry.key }.take(limit)
    }

    suspend fun recordSearchEvent(
        userId: String,
        queryText: String,
        selectedPlaceId: String?,
        selectedTitle: String?,
        source: SearchEventSource
    ): Result<Unit> = runCatching {
        val normalizedQuery = queryText.trim()
        if (normalizedQuery.isBlank()) return@runCatching

        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching

        dataSource.insertSearchActivity(
            SearchActivityInsert(
                userId = userRow.id,
                queryText = normalizedQuery,
                selectedPlaceId = selectedPlaceId,
                selectedTitle = selectedTitle,
                source = source.name
            )
        )
    }

    suspend fun recordCaptureByPlaceId(userId: String, placeId: String): Result<Unit> =
        runCatching {
            val normalizedPlaceId = placeId.trim()
            if (normalizedPlaceId.isBlank()) return@runCatching
            val captureXpAward = 120

            val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching
            val landmark =
                dataSource.fetchLandmarkByPlaceId(normalizedPlaceId) ?: throw IllegalStateException(
                    "This location is not mapped to a landmark yet."
                )

            val alreadyCaptured = dataSource.hasCaptureForUserAndLandmark(userRow.id, landmark.id)
            if (alreadyCaptured) return@runCatching

            dataSource.insertCapture(
                com.example.gotouchgrass.data.supabase.CaptureInsert(
                    userId = userRow.id,
                    zoneId = landmark.zoneId,
                    landmarkId = landmark.id,
                    rarityAtTime = rarityScoreForLandmarkCategoryName(landmark.category),
                    xpAwarded = captureXpAward
                )
            )

            // update user xp total on capture
            val newXpTotal = userRow.xpTotal + captureXpAward.toLong()
            dataSource.updateUserXpTotal(userId = userRow.id, newXpTotal = newXpTotal)
            val newLevel = (newXpTotal / 1000).toInt() + 1
            if (newLevel != userRow.level.toInt()) {
                dataSource.updateUserLevel(userRow.id, newLevel)
            }
        }

    suspend fun getMappedLandmarkCategoryForPlaceId(placeId: String): Result<String?> =
        runCatching {
            val normalizedPlaceId = placeId.trim()
            if (normalizedPlaceId.isBlank()) return@runCatching null
            dataSource.fetchLandmarkByPlaceId(normalizedPlaceId)?.category
        }

    suspend fun isPlaceMappedForCapture(placeId: String): Result<Boolean> = runCatching {
        getMappedLandmarkCategoryForPlaceId(placeId).getOrThrow() != null
    }

    suspend fun getLatestCaptureDateForPlaceId(
        userId: String, placeId: String
    ): Result<String?> = runCatching {
        val normalizedPlaceId = placeId.trim()
        if (normalizedPlaceId.isBlank()) return@runCatching null

        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching null
        val landmark =
            dataSource.fetchLandmarkByPlaceId(normalizedPlaceId) ?: return@runCatching null

        dataSource.fetchLatestCaptureByUserAndLandmark(userRow.id, landmark.id)?.capturedAt
    }

    suspend fun getCapturedPlaceIdsByUserId(userId: String): Result<Set<String>> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching emptySet()

        val capturedLandmarkIds = dataSource.fetchCapturedLandmarkIdsByUser(userRow.id)
        if (capturedLandmarkIds.isEmpty()) return@runCatching emptySet()

        dataSource.fetchLandmarksByIds(capturedLandmarkIds).map { it.placeId }.toSet()
    }

    // call this from real game events (zone capture, location visit, etc.)
    // TODO logic suggested by Claude Sonnet 4.6
    suspend fun recordChallengeProgress(
        userId: String, challengeId: Long, incrementBy: Double = 1.0
    ): Result<Unit> = runCatching {
        // TODO: look up user row by auth ID; return early if not found
        // TODO: fetch challenge row by challengeId
        // TODO: fetch existing challenge_progress for (userId, challengeId); return early if already completed
        // TODO: increment progress value by incrementBy, capped at target
        // TODO: upsert updated progress row (mark completedAt if newly finished)
        // TODO: if newly completed, attempt to insert challenge_xp_award (idempotency guard)
        // TODO: if award inserted, add rewardXp to user's xp_total and update user row
    }

    override suspend fun getCuratedRoutes(): Result<List<ExploreRouteItem>> = runCatching {
        val routes = dataSource.fetchRoutes()
        val stopsByRouteId = dataSource.fetchAllRouteStops().groupBy { it.routeId }

        routes.map { route ->
            val stops = (stopsByRouteId[route.id] ?: emptyList()).sortedBy { it.orderIndex }
            val stopStrings = stops.mapIndexed { idx, stop ->
                if (!stop.hintText.isNullOrBlank()) "${idx + 1}. ${stop.hintText}"
                else "Stop ${idx + 1}"
            }
            route.toExploreRouteItem(zoneCount = stops.size, routeStops = stopStrings)
        }
    }

    private fun ChallengeRow.toExploreChallengeItem(progress: ChallengeProgressRow?): ExploreChallengeItem {
        val progressValue = progress?.progressValue ?: 0.0
        val targetValue = extractTargetValue(ruleConfigJson.toString()) ?: 1.0
        val progressFraction = (progressValue / targetValue).coerceIn(0.0, 1.0).toFloat()
        val type =
            runCatching { ChallengeType.valueOf(challengeType) }.getOrDefault(ChallengeType.VISIT)

        return ExploreChallengeItem(
            id = id.toString(),
            title = title,
            description = description,
            rewardXp = rewardXp.toInt(),
            progress = "${formatValue(progressValue)} / ${formatValue(targetValue)}",
            progressFraction = progressFraction,
            challengeType = type
        )
    }

    private fun RouteRow.toExploreRouteItem(
        zoneCount: Int, routeStops: List<String>
    ): ExploreRouteItem {
        val parsedTheme =
            runCatching { RouteTheme.valueOf(theme) }.getOrDefault(RouteTheme.CITY_HIGHLIGHTS)
        val parsedDifficulty =
            runCatching { RouteDifficulty.valueOf(difficulty) }.getOrDefault(RouteDifficulty.EASY)
        return ExploreRouteItem(
            id = id.toString(),
            title = title,
            zoneCount = zoneCount,
            hours = estimatedDurationMinutes / 60.0,
            description = parsedTheme.toRouteDescription(),
            difficulty = parsedDifficulty,
            theme = parsedTheme,
            routeStops = routeStops
        )
    }

    private fun extractTargetValue(ruleConfigJson: String): Double? {
        return try {
            val json = JSONObject(ruleConfigJson)
            val targetKeys = listOf("uniqueZones", "distanceKm", "timeMinutes")
            for (key in targetKeys) {
                if (!json.has(key)) continue
                val value = json.optDouble(key, Double.NaN)
                if (value.isFinite() && value > 0.0) return value
            }
            null
        } catch (_: Exception) {
            null
        }
    }

    private fun formatValue(value: Double): String {
        return if (value % 1.0 == 0.0) value.toInt().toString() else "%.1f".format(value)
    }

    private fun RouteTheme.toRouteDescription(): String {
        return when (this) {
            RouteTheme.FOOD -> "Discover local food spots"
            RouteTheme.DRINKS -> "Find your next drink stop"
            RouteTheme.PARKS -> "Parks and green spaces nearby"
            RouteTheme.MURALS -> "Street art and mural highlights"
            RouteTheme.HIDDEN_STUDY_SPOTS -> "Quiet and hidden study places"
            RouteTheme.CITY_HIGHLIGHTS -> "Top city highlights to explore"
        }
    }

    suspend fun getUserSettings(userId: String): Result<UserPreferences> = runCatching {
        val userRow =
            dataSource.getUserRowByAuthId(userId) ?: return@runCatching defaultPreferences()
        val settingsRow =
            dataSource.fetchUserSettings(userRow.id) ?: return@runCatching defaultPreferences()
        UserPreferences(
            notificationsEnabled = settingsRow.notificationsEnabled,
            soundEffectsEnabled = settingsRow.soundEffectsEnabled,
            darkModeEnabled = settingsRow.darkModeEnabled,
            locationServicesEnabled = settingsRow.locationServicesEnabled
        )
    }

    suspend fun saveUserSettings(userId: String, prefs: UserPreferences): Result<Unit> =
        runCatching {
            val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching
            dataSource.upsertUserSettings(
                UserSettingsUpsert(
                    userId = userRow.id,
                    notificationsEnabled = prefs.notificationsEnabled,
                    soundEffectsEnabled = prefs.soundEffectsEnabled,
                    darkModeEnabled = prefs.darkModeEnabled,
                    locationServicesEnabled = prefs.locationServicesEnabled
                )
            )
        }

    private fun defaultPreferences() = UserPreferences(
        notificationsEnabled = true,
        soundEffectsEnabled = true,
        darkModeEnabled = false,
        locationServicesEnabled = true
    )

    suspend fun getLifetimeStats(userId: String): Result<LifetimeStats> = runCatching {
        val user = dataSource.getUserById(userId).getOrThrow() ?: return@runCatching LifetimeStats(
            totalXp = 0, coinsEarned = 0, totalDistanceKm = 0f, citiesExplored = 0
        )
        LifetimeStats(
            totalXp = user.xpTotal,
            coinsEarned = 0,        // TODO: fetch from coins table when available
            totalDistanceKm = 0f,   // TODO: compute from visit_session table when available
            citiesExplored = 0      // TODO: compute from city_completion table when available
        )
    }

    suspend fun getStreakData(userId: String): Result<StreakData> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching StreakData(
            currentDays = 0,
            bestDays = 0
        )
        val row = dataSource.fetchStreakByType(userRow.id, "DAILY_EXPLORE")
            ?: return@runCatching StreakData(currentDays = 0, bestDays = 0)
        StreakData(currentDays = row.currentCount, bestDays = row.bestCount)
    }

    suspend fun getWeeklySummary(userId: String): Result<WeeklySummary> = runCatching {
        val userRow =
            dataSource.getUserRowByAuthId(userId) ?: return@runCatching defaultWeeklySummary()

        val weekStartIso =
            LocalDate.now(ZoneOffset.UTC).with(DayOfWeek.MONDAY).atStartOfDay(ZoneOffset.UTC)
                .format(DateTimeFormatter.ISO_OFFSET_DATE_TIME)

        val sessions = dataSource.fetchWeeklyVisitSessions(userRow.id, weekStartIso)
        if (sessions.isEmpty()) return@runCatching defaultWeeklySummary()

        val totalSec = sessions.sumOf { it.durationSec }
        val totalHours = totalSec / 3600.0
        val timeOutside = if (totalHours < 1) "${totalSec / 60}m" else "%.1fh".format(totalHours)

        val zonesVisited = sessions.mapNotNull { it.zoneId }.distinct().size

        val dailySeconds = LongArray(7)
        sessions.forEach { session ->
            val day = runCatching {
                OffsetDateTime.parse(session.startedAt).dayOfWeek.value - 1
            }.getOrNull() ?: return@forEach
            dailySeconds[day] += session.durationSec
        }
        val maxSec = dailySeconds.max().takeIf { it > 0 } ?: 1L
        val dailyActivity = dailySeconds.map { (it.toFloat() / maxSec).coerceIn(0f, 1f) }

        val weeklyCaptures = dataSource.fetchWeeklyCaptures(userRow.id, weekStartIso)
        val weeklyXp = weeklyCaptures.sumOf { it.xpAwarded }

        WeeklySummary(
            timeOutside = timeOutside,
            zonesVisited = zonesVisited,
            xpEarned = weeklyXp,
            dailyActivity = dailyActivity
        )
    }

    private fun defaultWeeklySummary() = WeeklySummary(
        timeOutside = "0h",
        zonesVisited = 0,
        xpEarned = 0,
        dailyActivity = listOf(0f, 0f, 0f, 0f, 0f, 0f, 0f)
    )

    suspend fun getLeaderboard(currentUserId: String): Result<List<LeaderboardData>> = runCatching {
        val topUsers = dataSource.fetchLeaderboardUsers(20)
        val currentUserRow = dataSource.getUserRowByAuthId(currentUserId)

        val entries = topUsers.mapIndexed { index, userRow ->
            val isCurrentUser = userRow.authUserId == currentUserId
            LeaderboardData(
                rank = (index + 1).toString(),
                name = if (isCurrentUser) "You" else userRow.displayName,
                level = "Level ${userRow.level}",
                xp = "%,d XP".format(userRow.xpTotal),
                isGoldRank = index == 0,
                isCurrentUser = isCurrentUser
            )
        }.toMutableList()

        if (currentUserRow != null && topUsers.none { it.authUserId == currentUserId }) {
            entries.add(
                LeaderboardData(
                    rank = "...",
                    name = "You",
                    level = "Level ${currentUserRow.level}",
                    xp = "%,d XP".format(currentUserRow.xpTotal),
                    isGoldRank = false,
                    isCurrentUser = true
                )
            )
        }

        entries
    }

    // ── Trip / visit session ──────────────────────────────────────────────────

    suspend fun recordVisitSession(
        userId: String,
        startedAtIso: String,
        endedAtIso: String,
        durationSec: Long,
        dominantZoneId: Long?
    ): Result<Unit> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching
        dataSource.insertVisitSession(
            VisitSessionInsert(
                userId = userRow.id,
                zoneId = dominantZoneId,
                startedAt = startedAtIso,
                endedAt = endedAtIso,
                durationSec = durationSec,
                source = "AUTO"
            )
        )
    }

    suspend fun addXpForTrip(userId: String, xpAmount: Int): Result<Unit> = runCatching {
        if (xpAmount <= 0) return@runCatching
        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching
        val newXpTotal = userRow.xpTotal + xpAmount.toLong()
        dataSource.updateUserXpTotal(userId = userRow.id, newXpTotal = newXpTotal)
        val newLevel = (newXpTotal / 1000).toInt() + 1
        if (newLevel != userRow.level.toInt()) {
            dataSource.updateUserLevel(userRow.id, newLevel)
        }
    }

    suspend fun getZonesForTrip(): Result<List<TripZone>> = runCatching {
        dataSource.fetchAllZones().mapNotNull { row ->
            val polygon = parseZoneBoundingBox(row.boundingBox) ?: return@mapNotNull null
            TripZone(id = row.id, name = row.name, polygon = polygon)
        }
    }

    private fun parseZoneBoundingBox(element: kotlinx.serialization.json.JsonElement): List<LatLng>? {
        return try {
            val array = element.jsonArray
            if (array.isEmpty()) return null
            // Try [{lat:.., lng:..}] format first, then [[lat, lng]] format
            array.map { item ->
                val obj = item.jsonObject
                val lat = obj["lat"]?.jsonPrimitive?.content?.toDoubleOrNull()
                    ?: obj["latitude"]?.jsonPrimitive?.content?.toDoubleOrNull()
                val lng = obj["lng"]?.jsonPrimitive?.content?.toDoubleOrNull()
                    ?: obj["longitude"]?.jsonPrimitive?.content?.toDoubleOrNull()
                if (lat != null && lng != null) LatLng(lat, lng)
                else {
                    // Fallback: [[lat, lng], ...]
                    val inner = item.jsonArray
                    val lat2 = inner[0].jsonPrimitive.content.toDouble()
                    val lng2 = inner[1].jsonPrimitive.content.toDouble()
                    LatLng(lat2, lng2)
                }
            }
        } catch (_: Exception) {
            null
        }
    }

    suspend fun updateDailyExploreStreak(userId: String): Result<Int> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId) ?: return@runCatching 0
        val today = LocalDate.now(ZoneOffset.UTC)
        val existing = dataSource.fetchStreakByType(userRow.id, "DAILY_EXPLORE")
        val lastDate = existing?.lastCountedDate?.let {
            runCatching { LocalDate.parse(it) }.getOrNull()
        }

        // Already counted today — return current streak unchanged
        if (lastDate == today) return@runCatching existing?.currentCount ?: 1

        val newCount = if (lastDate == today.minusDays(1)) {
            (existing?.currentCount ?: 0) + 1  // consecutive day
        } else {
            1  // gap or first time
        }
        val bestCount = maxOf(newCount, existing?.bestCount ?: 0)

        dataSource.upsertStreak(
            StreakUpsert(
                userId = userRow.id,
                type = "DAILY_EXPLORE",
                currentCount = newCount,
                bestCount = bestCount,
                lastCountedDate = today.toString()
            )
        )
        newCount
    }

    suspend fun getFriendsApproxLocations(authUserId: String): Result<List<FriendMapMarker>> =
        runCatching {
            val currentUser = dataSource.getUserRowByAuthId(authUserId)
                ?: return@runCatching emptyList()
            val friendIds = dataSource.getUserFriends(currentUser.id)
            if (friendIds.isEmpty()) return@runCatching emptyList()

            val allUsers = dataSource.fetchLeaderboardUsers(1000)
            val friendUsers = allUsers.filter { it.id in friendIds }
            val allZones = dataSource.fetchAllZones()

            val markers = mutableListOf<FriendMapMarker>()
            for (friend in friendUsers) {
                val session = dataSource.fetchLatestZonedVisitSessionByUserId(friend.id) ?: continue
                val zoneId = session.zoneId ?: continue
                val zone = allZones.firstOrNull { it.id == zoneId } ?: continue
                val centroid = zoneCentroid(zone.boundingBox) ?: continue
                val initials = friend.displayName.trim().split(" ")
                    .mapNotNull { it.firstOrNull()?.uppercaseChar() }
                    .take(2).joinToString("")
                    .ifEmpty { friend.displayName.take(1).uppercase() }
                markers.add(FriendMapMarker(friend.displayName, initials, centroid))
            }
            markers
        }

    private fun zoneCentroid(element: kotlinx.serialization.json.JsonElement): GmsLatLng? {
        return try {
            val array = element.jsonArray
            if (array.isEmpty()) return null
            var sumLat = 0.0; var sumLng = 0.0; var count = 0
            for (item in array) {
                val obj = item.jsonObject
                val lat = obj["lat"]?.jsonPrimitive?.content?.toDoubleOrNull()
                    ?: obj["latitude"]?.jsonPrimitive?.content?.toDoubleOrNull()
                val lng = obj["lng"]?.jsonPrimitive?.content?.toDoubleOrNull()
                    ?: obj["longitude"]?.jsonPrimitive?.content?.toDoubleOrNull()
                if (lat != null && lng != null) { sumLat += lat; sumLng += lng; count++ }
            }
            if (count == 0) null else GmsLatLng(sumLat / count, sumLng / count)
        } catch (_: Exception) { null }
    }

    suspend fun getRouteStopLandmarks(routeId: Long): Result<List<Pair<Long, String>>> =
        runCatching {
            // Returns list of (landmarkId, placeId) for each stop that has a landmark
            val stops = dataSource.fetchRouteStopsByRouteId(routeId)
            val landmarkIds = stops.mapNotNull { it.landmarkId }
            if (landmarkIds.isEmpty()) return@runCatching emptyList()
            val landmarks = dataSource.fetchLandmarksByIds(landmarkIds)
            stops.sortedBy { it.orderIndex }.mapNotNull { stop ->
                val lm = landmarks.firstOrNull { it.id == stop.landmarkId } ?: return@mapNotNull null
                Pair(lm.id, lm.placeId)
            }
        }

    // friendship management

    suspend fun sendFriendRequest(
        authUserId: String,
        recipientAuthUserId: String
    ): Result<Unit> = runCatching {
        val requesterUser = dataSource.getUserRowByAuthId(authUserId)
            ?: throw Exception("Current user not found")
        val recipientUser = dataSource.getUserRowByAuthId(recipientAuthUserId)
            ?: throw Exception("Recipient user not found")
        dataSource.sendFriendRequest(requesterUser.id, recipientUser.id)
    }

    suspend fun getIncomingFriendRequests(authUserId: String): Result<List<Pair<FriendRequestRow, User>>> =
        runCatching {
            val currentUser = dataSource.getUserRowByAuthId(authUserId)
                ?: throw Exception("Current user not found")

            val requests = dataSource.getIncomingFriendRequests(currentUser.id)
            val requesterIds = requests.map { it.requesterId }
            val requesters = if (requesterIds.isNotEmpty()) {
                dataSource.fetchLeaderboardUsers(1000)
                    .filter { it.id in requesterIds }
            } else {
                emptyList()
            }

            val requesterMap = requesters.associateBy { it.id }.mapValues { (_, userRow) ->
                User(
                    id = userRow.authUserId,
                    displayName = userRow.displayName,
                    username = userRow.username,
                    email = userRow.email,
                    avatarUrl = userRow.avatarUrl,
                    createdAtIso = userRow.createdAt,
                    homeCityId = null,
                    level = userRow.level.toInt(),
                    xpTotal = userRow.xpTotal.toInt()
                )
            }

            requests.mapNotNull { request ->
                val user = requesterMap[request.requesterId]
                if (user != null) request to user else null
            }
        }

    suspend fun getOutgoingFriendRequests(authUserId: String): Result<List<Pair<FriendRequestRow, User>>> =
        runCatching {
            val currentUser = dataSource.getUserRowByAuthId(authUserId)
                ?: throw Exception("Current user not found")

            val requests = dataSource.getOutgoingFriendRequests(currentUser.id)
            val recipientIds = requests.map { it.recipientId }
            val recipients = if (recipientIds.isNotEmpty()) {
                dataSource.fetchLeaderboardUsers(1000)
                    .filter { it.id in recipientIds }
            } else {
                emptyList()
            }

            val recipientMap = recipients.associateBy { it.id }.mapValues { (_, userRow) ->
                User(
                    id = userRow.authUserId,
                    displayName = userRow.displayName,
                    username = userRow.username,
                    email = userRow.email,
                    avatarUrl = userRow.avatarUrl,
                    createdAtIso = userRow.createdAt,
                    homeCityId = null,
                    level = userRow.level.toInt(),
                    xpTotal = userRow.xpTotal.toInt()
                )
            }

            requests.mapNotNull { request ->
                val user = recipientMap[request.recipientId]
                if (user != null) request to user else null
            }
        }

    suspend fun declineFriendRequest(requestId: Long): Result<Unit> = runCatching {
        dataSource.declineFriendRequest(requestId)
    }

    suspend fun cancelFriendRequest(requestId: Long): Result<Unit> = runCatching {
        dataSource.cancelFriendRequest(requestId)
    }

    suspend fun acceptFriendRequest(requestId: Long): Result<Unit> = runCatching {
        dataSource.acceptFriendRequest(requestId)
    }

    suspend fun getFriends(authUserId: String): Result<List<User>> = runCatching {
        val currentUser = dataSource.getUserRowByAuthId(authUserId)
            ?: throw Exception("Current user not found")

        val friendIds = dataSource.getUserFriends(currentUser.id)
        if (friendIds.isEmpty()) return@runCatching emptyList()

        val allUsers = dataSource.fetchLeaderboardUsers(1000)
        allUsers
            .filter { it.id in friendIds }
            .map { userRow ->
                User(
                    id = userRow.authUserId,
                    displayName = userRow.displayName,
                    username = userRow.username,
                    email = userRow.email,
                    avatarUrl = userRow.avatarUrl,
                    createdAtIso = userRow.createdAt,
                    homeCityId = null,
                    level = userRow.level.toInt(),
                    xpTotal = userRow.xpTotal.toInt()
                )
            }
    }

    suspend fun removeFriend(
        authUserId: String,
        friendAuthUserId: String
    ): Result<Unit> = runCatching {
        val currentUser = dataSource.getUserRowByAuthId(authUserId)
            ?: throw Exception("Current user not found")
        val friendUser = dataSource.getUserRowByAuthId(friendAuthUserId)
            ?: throw Exception("Friend user not found")
        dataSource.removeFriend(currentUser.id, friendUser.id)
    }

    suspend fun isFriend(authUserId: String, otherUserId: Long): Result<Boolean> = runCatching {
        val currentUser = dataSource.getUserRowByAuthId(authUserId)
            ?: throw Exception("Current user not found")
        dataSource.isFriend(currentUser.id, otherUserId)
    }

    suspend fun searchUsers(query: String, limit: Int = 20): Result<List<User>> = runCatching {
        val userRows = dataSource.searchUsers(query, limit)
        userRows.map { userRow ->
            User(
                id = userRow.authUserId,
                displayName = userRow.displayName,
                username = userRow.username,
                email = userRow.email,
                avatarUrl = userRow.avatarUrl,
                createdAtIso = userRow.createdAt,
                homeCityId = null,
                level = userRow.level.toInt(),
                xpTotal = userRow.xpTotal.toInt()
            )
        }
    }

    suspend fun getFriendsLeaderboard(authUserId: String): Result<List<User>> = runCatching {
        val friends = getFriends(authUserId).getOrThrow()
        friends.sortedByDescending { it.xpTotal }
    }
}
