package com.example.gotouchgrass.data

import com.example.gotouchgrass.data.supabase.ChallengeProgressRow
import com.example.gotouchgrass.data.supabase.ChallengeRow
import com.example.gotouchgrass.data.supabase.RouteRow
import com.example.gotouchgrass.data.supabase.SearchActivityInsert
import com.example.gotouchgrass.data.supabase.SupabaseDataSource
import com.example.gotouchgrass.domain.ChallengeTimeWindow
import com.example.gotouchgrass.domain.ChallengeType
import com.example.gotouchgrass.domain.ExploreChallengeItem
import com.example.gotouchgrass.domain.ExploreRouteItem
import com.example.gotouchgrass.domain.RouteDifficulty
import com.example.gotouchgrass.domain.RouteTheme
import com.example.gotouchgrass.domain.User
import org.json.JSONObject

class GoTouchGrassRepository(
    private val dataSource: SupabaseDataSource
) {
    enum class SearchEventSource {
        RESULT,
        RECENT,
        TRENDING
    }

    // User
    suspend fun getUser(userId: String): Result<User?> = dataSource.getUserById(userId)

    // Explore page

    suspend fun getTotalXp(userId: String): Result<Int> = runCatching {
        dataSource.getUserById(userId).getOrThrow()?.xpTotal ?: 0
    }

    suspend fun getChallenges(
        userId: String,
        timeWindow: ChallengeTimeWindow
    ): Result<List<ExploreChallengeItem>> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId)
            ?: return@runCatching emptyList()

        val challenges = dataSource.fetchChallenges(timeWindow.name)
        val progressMap = dataSource.fetchChallengeProgress(userRow.id)
            .associateBy { it.challengeId }

        challenges.map { ch -> ch.toExploreChallengeItem(progressMap[ch.id]) }
    }

    suspend fun getRecentSearches(userId: String, limit: Int = 8): Result<List<String>> = runCatching {
        val userRow = dataSource.getUserRowByAuthId(userId)
            ?: return@runCatching emptyList()

        dataSource.fetchRecentSearchActivity(userRow.id, limit * 3)
            .map { it.queryText.trim() }
            .filter { it.isNotBlank() }
            .distinctBy { it.lowercase() }
            .take(limit)
    }

    // function logic generated by Claude Sonnet 4.6
    suspend fun getTrendingSearches(limit: Int = 5): Result<List<String>> = runCatching {
        val rows = dataSource.fetchRecentGlobalSearchActivity(300)
        val grouped = rows
            .map { it.queryText.trim() }
            .filter { it.isNotBlank() }
            .groupingBy { it.lowercase() }
            .eachCount()

        val canonicalByKey = rows
            .map { it.queryText.trim() }
            .filter { it.isNotBlank() }
            .associateBy { it.lowercase() }

        grouped.entries
            .sortedWith(compareByDescending<Map.Entry<String, Int>> { it.value }.thenBy { it.key })
            .map { entry -> canonicalByKey[entry.key] ?: entry.key }
            .take(limit)
    }

    suspend fun recordSearchEvent(
        userId: String,
        queryText: String,
        selectedPlaceId: String?,
        selectedTitle: String?,
        source: SearchEventSource
    ): Result<Unit> = runCatching {
        val normalizedQuery = queryText.trim()
        if (normalizedQuery.isBlank()) return@runCatching

        val userRow = dataSource.getUserRowByAuthId(userId)
            ?: return@runCatching

        dataSource.insertSearchActivity(
            SearchActivityInsert(
                userId = userRow.id,
                queryText = normalizedQuery,
                selectedPlaceId = selectedPlaceId,
                selectedTitle = selectedTitle,
                source = source.name
            )
        )
    }

    // call this from real game events (zone capture, location visit, etc.)
    // TODO logic suggested by Claude Sonnet 4.6
    suspend fun recordChallengeProgress(
        userId: String,
        challengeId: Long,
        incrementBy: Double = 1.0
    ): Result<Unit> = runCatching {
        // TODO: look up user row by auth ID; return early if not found
        // TODO: fetch challenge row by challengeId
        // TODO: fetch existing challenge_progress for (userId, challengeId); return early if already completed
        // TODO: increment progress value by incrementBy, capped at target
        // TODO: upsert updated progress row (mark completedAt if newly finished)
        // TODO: if newly completed, attempt to insert challenge_xp_award (idempotency guard)
        // TODO: if award inserted, add rewardXp to user's xp_total and update user row
    }

    suspend fun getCuratedRoutes(): Result<List<ExploreRouteItem>> = runCatching {
        val routes = dataSource.fetchRoutes()
        val stopsByRouteId = dataSource.fetchAllRouteStops().groupBy { it.routeId }

        routes.map { route ->
            val stops = (stopsByRouteId[route.id] ?: emptyList()).sortedBy { it.orderIndex }
            val stopStrings = stops.mapIndexed { idx, stop ->
                if (!stop.hintText.isNullOrBlank()) "${idx + 1}. ${stop.hintText}"
                else "Stop ${idx + 1}"
            }
            route.toExploreRouteItem(zoneCount = stops.size, routeStops = stopStrings)
        }
    }

    private fun ChallengeRow.toExploreChallengeItem(progress: ChallengeProgressRow?): ExploreChallengeItem {
        val progressValue = progress?.progressValue ?: 0.0
        val targetValue = extractTargetValue(ruleConfigJson.toString()) ?: 1.0
        val progressFraction = (progressValue / targetValue).coerceIn(0.0, 1.0).toFloat()
        val type =
            runCatching { ChallengeType.valueOf(challengeType) }.getOrDefault(ChallengeType.VISIT)

        return ExploreChallengeItem(
            id = id.toString(),
            title = title,
            description = description,
            rewardXp = rewardXp.toInt(),
            progress = "${formatValue(progressValue)} / ${formatValue(targetValue)}",
            progressFraction = progressFraction,
            challengeType = type
        )
    }

    private fun RouteRow.toExploreRouteItem(
        zoneCount: Int,
        routeStops: List<String>
    ): ExploreRouteItem {
        val parsedTheme =
            runCatching { RouteTheme.valueOf(theme) }.getOrDefault(RouteTheme.CITY_HIGHLIGHTS)
        val parsedDifficulty =
            runCatching { RouteDifficulty.valueOf(difficulty) }.getOrDefault(RouteDifficulty.EASY)
        return ExploreRouteItem(
            id = id.toString(),
            title = title,
            zoneCount = zoneCount,
            hours = estimatedDurationMinutes / 60.0,
            description = parsedTheme.toRouteDescription(),
            difficulty = parsedDifficulty,
            theme = parsedTheme,
            routeStops = routeStops
        )
    }

    private fun extractTargetValue(ruleConfigJson: String): Double? {
        return try {
            val json = JSONObject(ruleConfigJson)
            val targetKeys = listOf("uniqueZones", "distanceKm", "timeMinutes")
            for (key in targetKeys) {
                if (!json.has(key)) continue
                val value = json.optDouble(key, Double.NaN)
                if (value.isFinite() && value > 0.0) return value
            }
            null
        } catch (_: Exception) {
            null
        }
    }

    private fun formatValue(value: Double): String {
        return if (value % 1.0 == 0.0) value.toInt().toString() else "%.1f".format(value)
    }

    private fun RouteTheme.toRouteDescription(): String {
        return when (this) {
            RouteTheme.FOOD -> "Discover local food spots"
            RouteTheme.DRINKS -> "Find your next drink stop"
            RouteTheme.PARKS -> "Parks and green spaces nearby"
            RouteTheme.MURALS -> "Street art and mural highlights"
            RouteTheme.HIDDEN_STUDY_SPOTS -> "Quiet and hidden study places"
            RouteTheme.CITY_HIGHLIGHTS -> "Top city highlights to explore"
        }
    }
}
