package com.example.gotouchgrass.domain

import androidx.annotation.DrawableRes
import com.example.gotouchgrass.R

data class AvatarPreset(
    val key: String,
    val label: String,
    @param:DrawableRes @field:DrawableRes val drawableRes: Int
)

// labels generated by GPT-5.3-Codex
val avatarPresets: List<AvatarPreset> = listOf(
    AvatarPreset(key = "avatar_1", label = "Forest", drawableRes = R.drawable.avatar_preset_1),
    AvatarPreset(key = "avatar_2", label = "Sky", drawableRes = R.drawable.avatar_preset_2),
    AvatarPreset(key = "avatar_3", label = "Sunset", drawableRes = R.drawable.avatar_preset_3),
    AvatarPreset(key = "avatar_4", label = "Rose", drawableRes = R.drawable.avatar_preset_4),
    AvatarPreset(key = "avatar_5", label = "Stone", drawableRes = R.drawable.avatar_preset_5)
)

fun isValidAvatarPresetKey(key: String?): Boolean {
    if (key == null) return true
    return avatarPresets.any { it.key == key }
}

@DrawableRes
fun avatarDrawableResForKey(key: String?): Int? {
    if (key == null) return null
    return avatarPresets.firstOrNull { it.key == key }?.drawableRes
}
